### ISSUE TITLE
CDATA stripped from fields

### ISSUE THREAD

**Issue by bworrell** [STIXProject/python-stix#10] opened 2013-04-22 20:08 UTC
CDATA blocks are stripped on import. Export values are exposed without the CDATA encapsulation.

**Comment by chisholm** [comment] 2015-07-07 16:26
This is a cosmetic issue, not a bug.  The important thing is that content is preserved.  How escaping is done is an XML serialization detail, and not worth getting fancy and complicated to force one way or the other.  Closing as "wontfix".

**Closed by chisholm** 2015-07-07 16:26 UTC
Labels: wontfix
